/**
 * Fallback course data for when Supabase is unreachable.
 * Used ONLY as emergency resilience layer - Supabase is the source of truth.
 *
 * NOTE: This data is synced with the Google Sheets "Courses" tab.
 * All user management happens exclusively through Supabase.
 */
import type { Course } from './types';

export const FALLBACK_COURSES: Course[] = [
  {
    id: '1',
    title: 'Thiết kế website với Wordpress',
    description: 'Từ con số 0 đến website chuyên nghiệp chỉ trong 30 ngày! Khóa học giúp bạn tự tay xây dựng website bán hàng, landing page, blog cá nhân mà KHÔNG cần biết code. Bạn sẽ học cách chọn hosting, cài đặt Wordpress, thiết kế giao diện đẹp mắt với Elementor, tối ưu SEO và tăng tốc độ website. Hơn 1,500 học viên đã tạo website riêng sau khóa học này.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 1868000,
    originalPrice: 1868000,
    rating: 4.8,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 14,
    isFree: false,
    badge: 'BESTSELLER',
    category: 'Web Dev',
    memberLevel: 'Free',
  },
  {
    id: '2',
    title: 'Khởi nghiệp kiếm tiền online với AI',
    description: 'Khám phá cách tận dụng sức mạnh AI để xây dựng nguồn thu nhập thụ động! Từ ChatGPT, MidJourney đến các công cụ AI tự động - bạn sẽ học cách tạo content, viết copy bán hàng, thiết kế hình ảnh và xây dựng funnel kiếm tiền hoàn toàn bằng AI. Đã có hàng trăm học viên tạo thu nhập từ 10-50 triệu/tháng sau khóa học.',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 1868000,
    originalPrice: 3868000,
    rating: 4.9,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'BESTSELLER',
    category: 'AI',
    memberLevel: 'Free',
  },
  {
    id: '3',
    title: 'Xây dựng hệ thống Automation với N8N',
    description: 'Tự động hóa mọi quy trình kinh doanh - tiết kiệm 80% thời gian! Học cách sử dụng N8N (công cụ automation miễn phí) để tự động gửi email, đồng bộ dữ liệu, quản lý đơn hàng, chăm sóc khách hàng tự động. Không cần biết lập trình - chỉ cần kéo thả. Phù hợp cho chủ shop online, freelancer và doanh nghiệp nhỏ.',
    thumbnail: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 1868000,
    originalPrice: 3868000,
    rating: 4.7,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'NEW',
    category: 'Automation',
    memberLevel: 'Free',
  },
  {
    id: '4',
    title: 'Thiết kế hệ thống chatbot AI',
    description: 'Xây dựng chatbot AI thông minh - phục vụ khách hàng 24/7 không cần nhân viên! Bạn sẽ học cách tạo chatbot tư vấn sản phẩm, hỗ trợ khách hàng, chốt đơn tự động trên Website, Facebook Messenger và Zalo. Tích hợp ChatGPT để chatbot hiểu và trả lời tự nhiên như người thật. Giảm 70% chi phí nhân sự CSKH.',
    thumbnail: 'https://images.unsplash.com/photo-1531746790095-e5cb157f3086?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 1868000,
    originalPrice: 3868000,
    rating: 4.8,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    category: 'AI',
    memberLevel: 'Free',
  },
  {
    id: '5',
    title: 'Xây dựng hệ thống thu hút 1000 khách hàng tự động',
    description: 'Hệ thống marketing tự động giúp bạn có 1000 khách hàng tiềm năng mỗi tháng! Khóa học bật mí bí quyết xây dựng phễu marketing (funnel), chạy quảng cáo Facebook/Google hiệu quả, tạo lead magnet hấp dẫn và nuôi dưỡng khách hàng bằng email automation. Đã được kiểm chứng bởi hơn 200 doanh nghiệp.',
    thumbnail: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 3868000,
    originalPrice: 6868000,
    rating: 4.9,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'BESTSELLER',
    category: 'Marketing',
    memberLevel: 'Free',
  },
  {
    id: '6',
    title: 'Khởi nghiệp kiếm tiền với Youtube',
    description: 'Biến Youtube thành cỗ máy in tiền - từ 0 đến 100K subscribers! Học trọn bộ kỹ năng: lên ý tưởng content viral, quay dựng video chuyên nghiệp bằng điện thoại, tối ưu SEO Youtube, xây dựng thương hiệu cá nhân và kiếm tiền từ nhiều nguồn (Adsense, affiliate, tài trợ, bán khóa học). Phù hợp mọi lĩnh vực.',
    thumbnail: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 58868000,
    originalPrice: 58868000,
    rating: 4.6,
    reviewsCount: 0,
    enrollmentsCount: 150,
    duration: 16200,
    lessonsCount: 123,
    isFree: false,
    category: 'Marketing',
    memberLevel: 'VIP',
  },
  {
    id: '7',
    title: 'Vibe Code - Tạo ứng dụng với AI',
    description: 'Không biết code vẫn tạo được app! Khóa học hướng dẫn bạn sử dụng AI (Cursor, V0, Bolt) để xây dựng ứng dụng web và mobile từ A-Z. Từ ý tưởng đến sản phẩm hoàn chỉnh chỉ trong vài giờ. Bạn sẽ tạo được app quản lý, SaaS tool, marketplace... và có thể kiếm tiền ngay từ sản phẩm của mình.',
    thumbnail: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 3868000,
    originalPrice: 8868000,
    rating: 4.7,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'NEW',
    category: 'AI',
    memberLevel: 'Free',
  },
  {
    id: '8',
    title: 'Map To Success - Bản Đồ Đến Thành Công',
    description: 'Bản đồ chiến lược dành cho người muốn thành công trong kinh doanh online! Khóa học VIP giúp bạn xây dựng tư duy kinh doanh đúng đắn, lập kế hoạch chiến lược, phân tích thị trường, xây dựng đội nhóm và scale business lên 7 con số. Bao gồm mentoring 1-1 và cộng đồng mastermind độc quyền.',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 38868000,
    originalPrice: 68000000,
    rating: 4.9,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'PREMIUM',
    category: 'Business',
    memberLevel: 'VIP',
  },
  {
    id: '9',
    title: 'Business Automation Mystery',
    description: 'Bí mật tự động hóa kinh doanh triệu đô - dành riêng cho CEO và founders! Khóa học cao cấp nhất giúp bạn xây dựng hệ thống kinh doanh chạy tự động 24/7: từ marketing, bán hàng, chăm sóc khách hàng đến quản lý tài chính. Bao gồm 12 buổi coaching riêng, templates hệ thống trị giá 100 triệu và lifetime access.',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 300000000,
    originalPrice: 300000000,
    rating: 5,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'PREMIUM',
    category: 'Business',
    memberLevel: 'VIP',
  },
  {
    id: '10',
    title: 'Bản Đồ Kinh Doanh Triệu Đô',
    description: 'Lộ trình chi tiết từ 0 đến doanh thu 1 triệu USD! Đây là khóa học flagship của WePower Academy - tổng hợp 10 năm kinh nghiệm kinh doanh online. Bạn sẽ học cách chọn ngách, xây brand, tạo sản phẩm, marketing đa kênh, tối ưu vận hành và mở rộng quy mô. Kèm theo bộ công cụ và template business plan hoàn chỉnh.',
    thumbnail: 'https://images.unsplash.com/photo-1553729459-afe8f2e2882d?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 68868000,
    originalPrice: 99000000,
    rating: 4.9,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'PREMIUM',
    category: 'Business',
    memberLevel: 'VIP',
  },
  {
    id: '11',
    title: 'Business Internet System',
    description: 'Xây dựng hệ thống kinh doanh internet bài bản từ A đến Z! Khóa học hướng dẫn chi tiết cách tạo dựng business online hoàn chỉnh: website bán hàng, hệ thống email marketing, social media, quảng cáo trả phí, affiliate marketing và passive income. Phù hợp cho người mới bắt đầu muốn có thu nhập online ổn định.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 68680000,
    originalPrice: 68680000,
    rating: 4.8,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    category: 'Business',
    memberLevel: 'VIP',
  },
  {
    id: '12',
    title: 'Wellness To Wealth',
    description: 'Biến đam mê sức khỏe thành nguồn thu nhập bền vững! Khóa học dành cho ai yêu thích lĩnh vực wellness, fitness, dinh dưỡng muốn xây dựng thương hiệu cá nhân và kinh doanh online. Học cách tạo chương trình coaching, bán khóa học online, xây community và tạo passive income từ kiến thức wellness của bạn.',
    thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 68680000,
    originalPrice: 68680000,
    rating: 4.7,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    category: 'Lifestyle',
    memberLevel: 'VIP',
  },
  {
    id: '13',
    title: 'Unlock Your Power',
    description: 'Khai phá tiềm năng vô hạn bên trong bạn! Khóa học phát triển bản thân giúp bạn vượt qua rào cản tâm lý, xây dựng tư duy triệu phú, quản lý thời gian hiệu quả và phát triển kỹ năng lãnh đạo. Kết hợp NLP, coaching và mindfulness - đã thay đổi cuộc sống hàng ngàn người. Bắt đầu hành trình thay đổi ngay hôm nay!',
    thumbnail: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 1868000,
    originalPrice: 3500000,
    rating: 4.8,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'NEW',
    category: 'Lifestyle',
    memberLevel: 'Free',
  },
  {
    id: '14',
    title: 'Design With AI',
    description: 'Thiết kế đồ họa chuyên nghiệp với AI - nhanh gấp 10 lần! Không cần học Photoshop phức tạp - với MidJourney, DALL-E, Canva AI và các công cụ AI mới nhất, bạn có thể tạo logo, banner, social media post, ảnh sản phẩm chất lượng cao trong vài phút. Phù hợp cho marketer, chủ shop và freelancer thiết kế.',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 1868000,
    originalPrice: 3868000,
    rating: 4.6,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    category: 'AI',
    memberLevel: 'Free',
  },
  {
    id: '15',
    title: 'Master Video AI',
    description: 'Tạo video chuyên nghiệp bằng AI - không cần quay phim, không cần studio! Học cách sử dụng Runway, HeyGen, D-ID, CapCut AI để tạo video marketing, video bán hàng, video giáo dục chất lượng cao. Từ kịch bản AI, giọng đọc AI đến hình ảnh AI - tất cả trong một khóa học. Tiết kiệm hàng trăm triệu chi phí sản xuất video.',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800&h=450&fit=crop',
    instructor: 'WePower Academy',
    price: 3868000,
    originalPrice: 6868000,
    rating: 4.7,
    reviewsCount: 0,
    enrollmentsCount: 0,
    duration: 0,
    lessonsCount: 0,
    isFree: false,
    badge: 'NEW',
    category: 'AI',
    memberLevel: 'Free',
  },
];
